In [1]:
import pandas as pd 
import pickle 
from sklearn.metrics import confusion_matrix, precision_recall_curve, average_precision_score
from sklearn.metrics import auc, roc_auc_score, roc_curve, f1_score, accuracy_score, recall_score, precision_score, brier_score_loss
import numpy as np

In [2]:
seed = 561
test_datasets = [
    "test_data_full_cohort",
]

raw_results_dir = '../ufnet/'

df_test_datasets = []
for i in range(len(test_datasets)):
    with open(f'{raw_results_dir}{test_datasets[i]}_{seed}.pkl', 'rb') as pkl:
        f = pickle.load(pkl)
        all_labels = f['all_labels']
        all_final_predictions = f['all_final_predictions']
        all_pred_scores = f['all_pred_scores']
        uncertain_indices = f['uncertain_indices']
        all_final_std = f['all_final_std']
        
        all_pred_finger = all_pred_scores[0]
        all_pred_speech = all_pred_scores[1]
        all_pred_smile = all_pred_scores[2]
        
        print(len(all_labels), len(all_final_predictions), len(uncertain_indices), len(all_pred_finger))

    test_data = pd.read_csv(f'../../../data/{test_datasets[i]}.csv')
    test_data['true_label'] = all_labels
    test_data['pred_score_finger'] = all_pred_finger
    test_data['pred_score_speech'] = all_pred_speech
    test_data['pred_score_smile'] = all_pred_smile
    test_data['pred_score_fusion'] = all_final_predictions
    test_data['uncertain_indices'] = uncertain_indices
    test_data['test_split'] = test_datasets[i][8:-8]
    test_data['pred_std_fusion'] = all_final_std

    df_test_datasets.append(test_data)

test_df_full_cohort = pd.concat(df_test_datasets, axis=0)
test_df_full_cohort.head()

160 160 160 160

,row_id,id,label,true_label,pred_score_finger,pred_score_speech,pred_score_smile,pred_score_fusion,uncertain_indices,test_split,pred_std_fusion
0,NIHJW557ZEUZV#2022-10-20,NIHJW557ZEUZV,0.0,0.0,0.722253,0.138578,0.000679,0.000126,False,a_ful,0.000057
1,NIHJW557ZEUZV#2021-11-16,NIHJW557ZEUZV,0.0,0.0,0.157608,0.201683,0.134126,0.000216,False,a_ful,0.000104
2,UyTYPTilYMQB7pTCpNbsO5AUG6q2#2023-06-14,UyTYPTilYMQB7pTCpNbsO5AUG6q2,1.0,1.0,0.830535,0.815913,0.861023,0.998606,False,a_ful,0.000515
3,zibEntkmXAf3krIdZiOYTwrJbQZ2#2023-09-18,zibEntkmXAf3krIdZiOYTwrJbQZ2,1.0,1.0,0.235219,0.866811,0.812147,0.950767,False,a_ful,0.020503
4,zqnd36AIcmWYXY5wubKYnAxTRuo1#2021-11-05,zqnd36AIcmWYXY5wubKYnAxTRuo1,0.0,0.0,0.589939,0.229231,0.312566,0.371518,False,a_ful,0.061255

In [6]:
seed = 404
test_datasets = [
    "test_data_demo_matched",
]
raw_results_dir = '../../../../UFNet_Carrier_Classification_Demo_Matched/code_demo_matched/fusion_models/ufnet/'

df_test_datasets = []
for i in range(len(test_datasets)):
    with open(f'{raw_results_dir}{test_datasets[i]}_{seed}.pkl', 'rb') as pkl:
        f = pickle.load(pkl)
        all_labels = f['all_labels']
        all_final_predictions = f['all_final_predictions']
        all_pred_scores = f['all_pred_scores']
        uncertain_indices = f['uncertain_indices']
        all_final_std = f['all_final_std']
        
        all_pred_finger = all_pred_scores[0]
        all_pred_speech = all_pred_scores[1]
        all_pred_smile = all_pred_scores[2]
        
        print(len(all_labels), len(all_final_predictions), len(uncertain_indices), len(all_pred_finger))

    test_data = pd.read_csv(f'../../../../UFNet_Carrier_Classification_Demo_Matched/data/{test_datasets[i]}.csv')
    test_data['true_label'] = all_labels
    test_data['pred_score_finger'] = all_pred_finger
    test_data['pred_score_speech'] = all_pred_speech
    test_data['pred_score_smile'] = all_pred_smile
    test_data['pred_score_fusion'] = all_final_predictions
    test_data['uncertain_indices'] = uncertain_indices
    test_data['test_split'] = test_datasets[i][8:-8]
    test_data['pred_std_fusion'] = all_final_std

    df_test_datasets.append(test_data)

test_df_demo_matched = pd.concat(df_test_datasets, axis=0)
test_df_demo_matched.head()

77 77 77 77

,row_id,id,label,true_label,pred_score_finger,pred_score_speech,pred_score_smile,pred_score_fusion,uncertain_indices,test_split,pred_std_fusion
0,kXhCnVNXTUdi7PdLRzMfTscdSYq2#2023-08-19,kXhCnVNXTUdi7PdLRzMfTscdSYq2,1.0,1.0,0.709759,0.361505,0.200476,0.052358,False,a_demo,0.021013
1,XVBa44QtqbeYMBhalMoNv11GN9Z2#2023-09-20,XVBa44QtqbeYMBhalMoNv11GN9Z2,1.0,1.0,0.882874,0.829852,0.745600,0.975714,False,a_demo,0.003631
2,XVBa44QtqbeYMBhalMoNv11GN9Z2#2023-09-20,XVBa44QtqbeYMBhalMoNv11GN9Z2,1.0,1.0,0.832934,0.768455,0.795094,0.959244,False,a_demo,0.006995
3,NnueMgUo3IM8cGA6dZVx46yBSY72#2023-09-06,NnueMgUo3IM8cGA6dZVx46yBSY72,1.0,1.0,0.966667,0.544876,0.949984,0.987778,False,a_demo,0.003300
4,14GYE2DIFeRiie4h48KtjxOaijm1#2023-06-03,14GYE2DIFeRiie4h48KtjxOaijm1,1.0,1.0,0.916667,0.794691,0.090656,0.932141,False,a_demo,0.019627

In [7]:
test_df_full_cohort['test_split'] = 'full_data'
test_df_demo_matched['test_split'] = 'demo_matched'
test_df_final = pd.concat([test_df_full_cohort, test_df_demo_matched], axis=0)
test_df_final['test_split'].value_counts()

test_split
full_data       160
demo_matched     77
Name: count, dtype: int64

In [8]:
test_df_final.to_csv("../../../data/test_predictions_valor_pd_final.csv", index=False)

In [9]:
def safe_divide(numerator, denominator):
    if denominator == 0:
        return 0
    else:
        return numerator / denominator

In [10]:
def compute_metrics(y_true, y_pred_scores, threshold = 0.5):
    labels = np.asarray(y_true).reshape(-1)
    pred_scores = np.asarray(y_pred_scores).reshape(-1)
    preds = (pred_scores >= threshold)


    metrics = {}
    metrics['accuracy'] = accuracy_score(labels, preds)
    metrics['average_precision'] = average_precision_score(labels, pred_scores)
    metrics['auroc'] = roc_auc_score(labels, pred_scores)
    metrics['f1_score'] = f1_score(labels, preds)
    
    tn, fp, fn, tp = confusion_matrix(labels, preds).ravel()
    metrics["confusion_matrix"] = {"tn":tn, "fp":fp, "fn":fn, "tp":tp}
    metrics["weighted_accuracy"] = (safe_divide(tp, tp + fp) + safe_divide(tn, tn + fn)) / 2.0

    '''
    True positive rate or recall or sensitivity: probability of identifying a positive case 
    (often called the power of a test)
    '''
    metrics['TPR'] = metrics['recall'] = metrics['sensitivity'] = recall_score(labels, preds)
    
    '''
    False positive rate: probability of falsely identifying someone as positive, who is actually negative
    '''
    metrics['FPR'] = safe_divide(fp, fp+tn)
    
    '''
    Positive Predictive Value: probability that a patient with a positive test result 
    actually has the disease
    '''
    metrics['PPV'] = metrics['precision'] = precision_score(labels, preds)
    
    '''
    Negative predictive value: probability that a patient with a negative test result 
    actually does not have the disease
    '''
    metrics['NPV'] = safe_divide(tn, tn+fn)
    
    '''
    True negative rate or specificity: probability of a negative test result, 
    conditioned on the individual truly being negative
    '''
    metrics['TNR'] = metrics['specificity'] = safe_divide(tn,(tn+fp))

    
    return metrics

In [11]:
compute_metrics(test_df_full_cohort['true_label'], test_df_full_cohort['pred_score_fusion'], threshold = 0.5)

{'accuracy': 0.9125,
 'average_precision': 0.8218704692032506,
 'auroc': 0.9169921875,
 'f1_score': 0.7878787878787878,
 'confusion_matrix': {'tn': 120, 'fp': 8, 'fn': 6, 'tp': 26},
 'weighted_accuracy': 0.8585434173669467,
 'TPR': 0.8125,
 'recall': 0.8125,
 'sensitivity': 0.8125,
 'FPR': 0.0625,
 'PPV': 0.7647058823529411,
 'precision': 0.7647058823529411,
 'NPV': 0.9523809523809523,
 'TNR': 0.9375,
 'specificity': 0.9375}

In [12]:
test_df_full_cohort_certain = test_df_full_cohort[~test_df_full_cohort['uncertain_indices']]
compute_metrics(test_df_full_cohort_certain['true_label'], test_df_full_cohort_certain['pred_score_fusion'], threshold = 0.5)

{'accuracy': 0.9290322580645162,
 'average_precision': 0.8225192811141959,
 'auroc': 0.9170666666666667,
 'f1_score': 0.8135593220338984,
 'confusion_matrix': {'tn': 120, 'fp': 5, 'fn': 6, 'tp': 24},
 'weighted_accuracy': 0.8899835796387521,
 'TPR': 0.8,
 'recall': 0.8,
 'sensitivity': 0.8,
 'FPR': 0.04,
 'PPV': 0.8275862068965517,
 'precision': 0.8275862068965517,
 'NPV': 0.9523809523809523,
 'TNR': 0.96,
 'specificity': 0.96}

In [13]:
compute_metrics(test_df_demo_matched['true_label'], test_df_demo_matched['pred_score_fusion'], threshold = 0.5)

{'accuracy': 0.8181818181818182,
 'average_precision': 0.9057561235556875,
 'auroc': 0.9224489795918367,
 'f1_score': 0.8205128205128205,
 'confusion_matrix': {'tn': 31, 'fp': 11, 'fn': 3, 'tp': 32},
 'weighted_accuracy': 0.8279753761969904,
 'TPR': 0.9142857142857143,
 'recall': 0.9142857142857143,
 'sensitivity': 0.9142857142857143,
 'FPR': 0.2619047619047619,
 'PPV': 0.7441860465116279,
 'precision': 0.7441860465116279,
 'NPV': 0.9117647058823529,
 'TNR': 0.7380952380952381,
 'specificity': 0.7380952380952381}

In [14]:
test_df_demo_matched_certain = test_df_demo_matched[~test_df_demo_matched['uncertain_indices']]
compute_metrics(test_df_demo_matched_certain['true_label'], test_df_demo_matched_certain['pred_score_fusion'], threshold = 0.5)

{'accuracy': 0.863013698630137,
 'average_precision': 0.9104416297513661,
 'auroc': 0.9233082706766917,
 'f1_score': 0.8648648648648649,
 'confusion_matrix': {'tn': 31, 'fp': 7, 'fn': 3, 'tp': 32},
 'weighted_accuracy': 0.8661387631975868,
 'TPR': 0.9142857142857143,
 'recall': 0.9142857142857143,
 'sensitivity': 0.9142857142857143,
 'FPR': 0.18421052631578946,
 'PPV': 0.8205128205128205,
 'precision': 0.8205128205128205,
 'NPV': 0.9117647058823529,
 'TNR': 0.8157894736842105,
 'specificity': 0.8157894736842105}